# Generated by Django 4.1.7 on 2023-08-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='who_asked',
        ),
        migrations.RemoveField(
            model_name='help',
            name='who_complete',
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Help',
        ),
    ]
