# Generated by Django 4.1.7 on 2023-07-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.customuser',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.customuser',),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_fact',
            field=models.CharField(default='def', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_reg',
            field=models.CharField(default='def', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='form',
            field=models.CharField(default='def', max_length=32),
        ),
        migrations.AddField(
            model_name='customuser',
            name='head',
            field=models.CharField(default='def', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='inn',
            field=models.CharField(default='def', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_blago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_rest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kpp',
            field=models.CharField(default='def', max_length=9, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ogrn',
            field=models.CharField(default='def', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(default='def', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='def', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
