# Generated by Django 4.2.3 on 2023-07-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_ind_pred',
            field=models.BooleanField(default=False),
        ),
    ]
