# Generated by Django 4.1.7 on 2023-07-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_fund_restaurant_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='def', max_length=50, null=True),
        ),
    ]
