# Generated by Django 4.1.7 on 2023-07-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='inn',
            field=models.CharField(default='def', max_length=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='kpp',
            field=models.CharField(default='def', max_length=9),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ogrn',
            field=models.CharField(default='def', max_length=15),
        ),
    ]
