# Generated by Django 4.1.7 on 2023-07-10 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_otpmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='otpmodel',
            name='is_active',
        ),
    ]
