# Generated by Django 4.1.7 on 2023-07-11 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_otpmodel_created_at_remove_otpmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
