# Generated by Django 4.1.7 on 2023-07-13 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_otpmodel_created_at_otpmodel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='def', max_length=255)),
                ('full_info', models.TextField(default='def')),
                ('pubdate', models.DateTimeField(auto_now_add=True)),
                ('org_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
