# Generated by Django 4.1.7 on 2023-07-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_help'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='org_info',
        ),
    ]
