# Generated by Django 4.2.3 on 2023-07-26 13:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_help_org_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
