# Generated by Django 4.2.3 on 2023-07-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_delete_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='def', max_length=255)),
                ('full_info', models.TextField(default='def')),
                ('pubdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
