# Generated by Django 4.1.7 on 2023-07-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('full_info', models.TextField(verbose_name='Подробное описание')),
                ('org_info', models.TextField(verbose_name='Описание организации')),
                ('pubdate', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
