# Generated by Django 4.1.7 on 2023-09-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='deadline_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
