# Generated by Django 4.1.7 on 2023-09-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_help_deadline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
