# Generated by Django 4.1.7 on 2023-09-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_phishinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishinglog',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1'),
            preserve_default=False,
        ),
    ]
