# Generated by Django 4.1.7 on 2023-09-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_phishinglog_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishinglog',
            name='ip_address',
            field=models.CharField(max_length=20),
        ),
    ]
