# Generated by Django 4.1.7 on 2023-09-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_phishinglog_ip_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhishingLog',
        ),
    ]
